#ifndef GALLARYCORE_GLOBAL_H
#define GALLARYCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GALLARYCORE_LIBRARY)
#  define GALLARYCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GALLARYCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GALLARYCORE_GLOBAL_H
